### ISSUE TITLE
Release Minimig 0.11.0

### ISSUE THREAD

**Issue by Jaxelr** [Jaxelr/Minimig#221]

**Comment by Jaxelr** [comment]
I have the following modifications I want to do before releasing:

- [ ] Add parameter comments to methods/functions
- [ ] modify ifs to follow consistent pattern for single line ifs
- [ ] Add comments to functions where needed

**Comment by Jaxelr** [comment]
This is just missing a refactor on the tests that I should be able to sort out tomorrow and thats releasing version 0.11.0.

**Comment by yairvogel** [comment]
Hello @Jaxelr! will the next version support .net 8 sdk? looks like it is supported only by .net5 which is already unsupported. Thank you!

**Comment by Jaxelr** [comment]
hey @yairvogel yes, I'll support net 6 and 8 :) and it should be live.
